<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Variables -->
    <xacro:property name="base_leg_length" value="0.005" />
    <xacro:property name="base_leg_width" value="0.005" />
    <xacro:property name="base_leg_height" value="0.001" />
    <xacro:property name="shoulder_length" value="0.02" />
    <xacro:property name="shoulder_radius" value="0.01" />
    <xacro:property name="thigh_radius" value="0.005" />
    <xacro:property name="thigh_length" value="0.05" />
    <xacro:property name="shank_radius" value="0.005" />
    <xacro:property name="shank_length" value="0.04" />

    <!-- Function: Create base link -->
    <xacro:macro name="base_link" params="prefix">
        <link name="${prefix}_base_link">
            <visual>
                <geometry>
                    <box size="${base_leg_length} ${base_leg_width} ${base_leg_height}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="yellow" />
            </visual>
        </link>
    </xacro:macro>

    <!-- Function: Create shoulder link -->
    <xacro:macro name="shoulder_link" params="prefix">
        <link name="${prefix}_shoulder_link">
            <visual>
                <geometry>
                    <cylinder radius="${shoulder_radius}" length="${shoulder_length}" />
                </geometry>
                <origin xyz="0 0 ${-shoulder_length/2}" rpy="0 0 0" />
                <material name="orange" />
            </visual>
        </link>
    </xacro:macro>

    <!-- Function: Create upper leg -->
    <xacro:macro name="thigh_link" params="prefix">
        <link name="${prefix}_thigh_link">
            <visual>
                <geometry>
                    <cylinder radius="${thigh_radius}" length="${thigh_length}" />
                </geometry>
                <origin xyz="0 0 ${thigh_length / 2.0}" rpy="0 0 0" />
                <material name="yellow" />
            </visual>
        </link>
    </xacro:macro>

    <!-- Function: Create lower leg -->
    <xacro:macro name="shank_link" params="prefix">
        <link name="${prefix}_shank_link">
            <visual>
                <geometry>
                    <cylinder radius="${shank_radius}" length="${shank_length}" />
                </geometry>
                <origin xyz="0 0 ${shank_length / 2.0}" rpy="0 0 0" />
                <material name="orange" />
            </visual>
        </link>
    </xacro:macro>

    <!-- Function: shoulder joint -->
    <xacro:macro name="shoulder_joint" params="prefix">
        <joint name="${prefix}_shoulder_joint" type="revolute">
            <parent link="${prefix}_base_link" />
            <child link="${prefix}_shoulder_link" />
            <origin xyz="0 0 ${base_leg_height/2}" rpy="${pi/2} ${pi/2} 0" />
            <axis xyz="0 1 0" />
            <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="100" />
        </joint>
    </xacro:macro>

    <!-- Function: elbow joint -->
    <xacro:macro name="elbow_joint" params="prefix">
        <joint name="${prefix}_elbow_joint" type="revolute">
            <parent link="${prefix}_shoulder_link" />
            <child link="${prefix}_thigh_link" />
            <origin xyz="0 0 ${-shoulder_length}" rpy="0 ${pi/2} 0" />
            <axis xyz="1 0 0" />
            <limit lower="${-pi/3}" upper="${pi/3}" effort="100" velocity="100" />
        </joint>
    </xacro:macro>

    <!-- Function: wrist joint -->
    <xacro:macro name="wrist_joint" params="prefix">
        <joint name="${prefix}_wrist_joint" type="revolute">
            <parent link="${prefix}_thigh_link" />
            <child link="${prefix}_shank_link" />
            <origin xyz="0 0 ${thigh_length}" rpy="0 0 0" />
            <axis xyz="1 0 0" />
            <limit lower="0" upper="${3*pi/4}" effort="100" velocity="100" />
        </joint>
    </xacro:macro>

    <!-- Function: Create full leg with joints -->
    <xacro:macro name="generate_leg" params="prefix">
        <xacro:base_link prefix="${prefix}" />
        <xacro:shoulder_link prefix="${prefix}" />
        <xacro:thigh_link prefix="${prefix}" />
        <xacro:shank_link prefix="${prefix}" />
        <xacro:shoulder_joint prefix="${prefix}" />
        <xacro:elbow_joint prefix="${prefix}" />
        <xacro:wrist_joint prefix="${prefix}" />
    </xacro:macro>

</robot>