<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:include filename="leg.xacro" />

    <xacro:property name="base_length" value="0.15" />
    <xacro:property name="base_width" value="0.1" />
    <xacro:property name="base_height" value="0.03" />

    <!-- Function: base-leg joint -->
    <xacro:macro name="base_leg_joint" params="prefix x y">
        <joint name="base_${prefix}_leg_joint" type="fixed">
            <parent link="base_link" />
            <child link="${prefix}_base_link" />
            <origin xyz="${x} ${y} ${base_height/2.0}" rpy="0 0 0" />
        </joint>
    </xacro:macro>

    <!-- Create base link -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>

    <!-- Create legs using function in 'leg.xacro' -->
    <xacro:generate_leg prefix="fr" />
    <xacro:generate_leg prefix="fl" />
    <xacro:generate_leg prefix="rr" />
    <xacro:generate_leg prefix="rl" />

    <!-- Connect legs to base_link -->
    <xacro:base_leg_joint prefix="fr" x="${-0.01+base_length/2}" y="${-base_width/2}" />
    <xacro:base_leg_joint prefix="fl" x="${-0.01+base_length/2}" y="${base_width/2}" />
    <xacro:base_leg_joint prefix="rr" x="${0.01-base_length/2}" y="${-base_width/2}" />
    <xacro:base_leg_joint prefix="rl" x="${0.01-base_length/2}" y="${base_width/2}" />

    

</robot>